from .base_check import BaseCheck
import re

class WAFDetectorCheck(BaseCheck):
    """Detect Web Application Firewalls and security products"""

    def __init__(self):
        super().__init__()
        self.name = "WAF Detector"
        self.description = "Detects web application firewalls and security middleware"

        self.waf_signatures = {
            'Cloudflare': {
                'headers': ['cf-ray', 'cf-cache-status', '__cfduid', 'cf-request-id'],
                'body': ['cloudflare', 'attention required', 'cf-browser-verification'],
                'server': ['cloudflare']
            },
            'Akamai': {
                'headers': ['x-akamai-transformed', 'akamai-origin-hop'],
                'body': ['akamai', 'access denied - akamai'],
                'server': ['akamaighost', 'akamai']
            },
            'AWS WAF': {
                'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
                'body': ['aws', 'x-amz-'],
                'server': ['awselb']
            },
            'ModSecurity': {
                'headers': ['x-mod-security', 'mod_security'],
                'body': ['mod_security', 'modsecurity', 'noyb'],
                'server': ['mod_security']
            },
            'Sucuri': {
                'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                'body': ['sucuri', 'sucuri website firewall'],
                'server': ['sucuri']
            },
            'Wordfence': {
                'headers': [],
                'body': ['wordfence', 'generated by wordfence', 'wfwaf-'],
                'server': []
            },
            'Imperva/Incapsula': {
                'headers': ['x-iinfo', 'x-cdn'],
                'body': ['incapsula', 'imperva'],
                'server': ['incapsula']
            },
            'F5 BIG-IP': {
                'headers': ['x-wa-info', 'x-cnection'],
                'body': [],
                'server': ['bigip', 'big-ip', 'f5']
            },
            'DDoS-Guard': {
                'headers': [],
                'body': ['ddos-guard'],
                'server': ['ddos-guard']
            },
            'Varnish': {
                'headers': ['x-varnish', 'via'],
                'body': [],
                'server': ['varnish']
            }
        }

    def run(self, target, tor_session, config=None):
        findings = []

        url = target if target.startswith('http') else 'http://' + target
        timeout = config.get('timeout', 10) if config else 10

        # Normal request
        resp = tor_session.get(url, timeout=timeout)
        if not resp:
            return findings

        detected_wafs = []
        headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
        body_lower = resp.text.lower() if resp.text else ''
        server_header = headers_lower.get('server', '')

        for waf_name, sigs in self.waf_signatures.items():
            detected = False

            # Check headers
            for header in sigs['headers']:
                if header.lower() in headers_lower:
                    detected = True
                    break

            # Check server header
            if not detected:
                for server_sig in sigs['server']:
                    if server_sig.lower() in server_header:
                        detected = True
                        break

            # Check body
            if not detected:
                for body_sig in sigs['body']:
                    if body_sig.lower() in body_lower:
                        detected = True
                        break

            if detected:
                detected_wafs.append(waf_name)

        # Send a request that looks suspicious to WAFs but is harmless.
        # FIX: Previously this sent a real SQL injection payload (?id=1'+OR+1=1--).
        # If the target had no WAF, this could actually exploit a vulnerable parameter.
        # A scanner should probe for WAF presence, not attack the target.
        # Using a clearly fake path with suspicious keywords is enough to trigger
        # WAF rules without risking actual exploitation.
        trigger_url = url.rstrip('/') + "/test?foo=<script>alert(1)</script>"
        trigger_resp = tor_session.get(trigger_url, timeout=timeout)

        blocked = False
        if trigger_resp:
            # WAF typically returns 403, 406, or custom block pages
            if trigger_resp.status_code in [403, 406, 429, 503]:
                blocked = True
            block_indicators = ['blocked', 'forbidden', 'access denied', 'security policy',
                                 'request blocked', 'malicious', 'suspicious activity',
                                 'waf', 'firewall', 'protection']
            if any(ind in trigger_resp.text.lower() for ind in block_indicators):
                blocked = True

        if detected_wafs:
            findings.append({
                'check': self.name,
                'severity': 'info',
                'finding': f"WAF detected: {', '.join(detected_wafs)}",
                'detail': 'Web Application Firewall identified via headers/signatures',
                'url': url,
                'data': {'wafs': detected_wafs}
            })

        if blocked:
            findings.append({
                'check': self.name,
                'severity': 'info',
                'finding': 'WAF actively blocking: SQLi test request was rejected',
                'detail': f'Trigger URL returned HTTP {trigger_resp.status_code}',
                'url': url
            })
        elif trigger_resp and trigger_resp.status_code == 200:
            findings.append({
                'check': self.name,
                'severity': 'medium',
                'finding': 'No WAF blocking detected: SQLi test request passed through',
                'detail': 'Site may lack input filtering',
                'url': url
            })

        # Check for interesting security headers from the WAF
        security_products = []
        for header in ['x-powered-by', 'x-aspnet-version', 'x-runtime', 'x-generator']:
            if header in headers_lower:
                security_products.append(f"{header}: {headers_lower[header]}")

        if security_products:
            findings.append({
                'check': self.name,
                'severity': 'low',
                'finding': f"Technology disclosure via headers: {len(security_products)}",
                'detail': '\n'.join(security_products),
                'url': url
            })

        return findings
